# Generated by Django 2.0.2 on 2018-06-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='picname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
