# Generated by Django 2.0.2 on 2018-06-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180623_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/anncpic'),
        ),
    ]
