# Generated by Django 2.0.2 on 2018-06-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_announcement_picname'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('team_limit', models.IntegerField()),
                ('size_limit', models.IntegerField()),
            ],
        ),
    ]
