# Generated by Django 2.0.2 on 2018-06-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_sportsevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsevent',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
