# Generated by Django 2.0.2 on 2018-06-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_sportsevent_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsevent',
            name='start_date',
            field=models.DateField(),
        ),
    ]
