# Generated by Django 2.0.2 on 2018-06-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20180624_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsevent',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
