# Generated by Django 2.0.2 on 2018-06-24 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20180624_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='student_id',
            new_name='students',
        ),
    ]
